language: python

# See: https://docs.travis-ci.com/user/languages/python/
# Since we need the native python3-pyqt5 system-site package, we only have
# access to the natively supported python versions on each distribution:
sudo: true
matrix:
  include:
    - {python: "3.4", dist: trusty}
    - {python: "3.5", dist: xenial}
  # - {python: "3.6", dist: bionic}

# Dependencies can be installed as follows. This works only for packages
# whitelisted on https://github.com/travis-ci/apt-package-whitelist:
addons:
  apt:
    packages:
      - python3-pyqt5

virtualenv:
  system_site_packages: true

# We don't have real tests for now, so do flake8 (=pyflakes+pycodestyle+mccabe)
# sanity checks at least (note that I found mypy/pylint much too noisy…):
install:
  - pip install flake8 docutils pygments
  - flake8
  - python setup.py check -rs

  - pip install pytest
  - git clone git://github.com/hibtc/hit_models

  # Check that the source distribution can be used for installation -
  # without having *any* dependencies installed:
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)
  # Need to remove source folder otherwise it will be imported, but we want
  # to check the version installed from the source distribution:
  - rm -r madgui

script:
  - pytest tests

# Enable caching of python wheels
env:
  global:
    - PIP_FIND_LINKS=file://$HOME/.pip-cache
    - PIP_WHEEL_DIR=$HOME/.pip-cache

cache:
  apt: true
  directories:
    - $PIP_WHEEL_DIR
