language: python

# See: https://docs.travis-ci.com/user/languages/python/
python:
  - "3.4"
  - "3.5"
  - "3.6"

# For now, we don't have tests, so do pyflakes sanity checks at least:
# (Note that I found mypy/pep8 etc much too verbose…)

install:
  - pip install pyflakes pycodestyle

script:
  - pyflakes madgui
  - pycodestyle madgui --select E127,E128,E231,E261,E265,E301,E302,E303,E306,W391
