language: python

# See: https://docs.travis-ci.com/user/languages/python/
python:
  - "3.4"
  - "3.5"
  - "3.6"

# We don't have real tests for now, so do flake8 (=pyflakes+pycodestyle+mccabe)
# sanity checks at least (note that I found mypy/pylint much too noisy…):
install:
  - pip install flake8

script:
  - flake8
