language: python

sudo: true
# Dependencies can be installed as follows. This works only for packages
# whitelisted on https://github.com/travis-ci/apt-package-whitelist:
addons:
  apt:
    packages:
      - python3-pyqt5

virtualenv:
  system_site_packages: true

# We don't have real tests for now, so do flake8 (=pyflakes+pycodestyle+mccabe)
# sanity checks at least (note that I found mypy/pylint much too noisy…):
install:
  - pip install flake8 docutils pygments
  - flake8
  - python setup.py check -rs

  - pip install pytest
  - git clone git://github.com/hibtc/hit_models

  # Check that the source distribution can be used for installation -
  # without having *any* dependencies installed:
  - python setup.py sdist
  - pip install $(ls ./dist/*.tar.gz | sort -rV | head -n1)

script:
  - pytest tests


# See: https://docs.travis-ci.com/user/languages/python/
# Since we need the native python3-pyqt5 system-site package, we only have
# access to the natively supported python versions on each distribution:
jobs:
  include:
    - {python: "3.4", dist: trusty}
    - {python: "3.5", dist: xenial}
  # - {python: "3.6", dist: bionic}

    - stage: deploy
      python: "3.4"
      dist: trusty
      name: Upload Documentation
      install:
        - pip install sphinx sphinx_rtd_theme
        - python setup.py develop
      script:
        - make -C docs html
      deploy:
        - provider: pages
          local-dir: docs/_build/html
          skip-cleanup: true
          github-token:
            secure: "kMSU+klQmq83Rc/N9trJQ0C8yCNNzzrskoGrFWlnB7pOQoSM4EhYHj1qhWUwBRrx7603EowKU/vmdOftlf59V/QbnQ2cCB8ddVHwNBqD+BWm3aToaltjTnXbaVtevvV07l07lO9oEHThHlDdAp2yr29NrH2d/tZ+g99PGYvbQcClCJlWyDP/7AdZVRV5ZneEpD8DemAGV2TBd8r/HOVp5piQQ73m+MOAYxt98V/Yvn/HobQ3Ui9JtlvFbkqLGPBDUNFdUuVjFqpk0PquZcO8cer87Dir0YPWVFal0L4mUOzQljxBRpL/koCz1FGubgutzDYawzXQzCl5TXvHIunUFMUMt4r8n+pSJOw37FTE/T3wnaVLVyMS6PdCTf2fPBVnzRLNKOM+0nRjypecmhEf/txhHQY+RdhbwuIjUYBIZB1YQbXE+xL2kFH9gwfReDDSUOWKZYe3iJwRvFlkpq1qNyDdcA70o2ZkrvNazn8P+YyK63m9ttY6IDjeq5xFBd8hvaqR7/LLQSHRzznr+UMZtboxIbZI/4TjGPPMI/0tEO/ILfeob3D5QphJjigRW0Vgt4Ksv1oFEpGUNLSP5z7IwdRt7gvMi9KBGblAOPGbmcJafvScCfKLJRhwo6wgB5zvbxwcckSURPqGbUFEu/IbJvKuXNlBvShfnoePw2Kt21A="
          on:
            branch: master

cache:
  pip: true
