line_view:

  # name of a unit in ``unum.units``
  unit:
    s: "m"
    envx: "mm"
    envy: "mm"

  label:
    s: "position $s$"
    envx: "$\\Delta x$"
    envy: "$\\Delta y$"

  # keyword arguments to ``matplotlib.axes.plot()``
  curve_style:
    x:
      color: "#8b1a0e"
      marker: "o"
      fillstyle: "none"
      linestyle: "-"

    y:
      color: "#5e9c36"
      marker: "o"
      fillstyle: "none"
      linestyle: "-"

  # keyword arguments to ``matplotlib.patches.Rectangle()`` and
  # ``matplotlib.axes.vlines()``:
  element_style:
    f-quadrupole: {color: "#ff0000", alpha: 0.5}
    d-quadrupole: {color: "#0000ff", alpha: 0.5}
    f-sbend:      {color: "#770000", alpha: 0.5}
    d-sbend:      {color: "#000077", alpha: 0.5}
    multipole:    {color: "#00ff00", alpha: 0.5}
    solenoid:     {color: "#555555", alpha: 0.5}
